### ISSUE TITLE
允许返回 JSON 而非 event stream

### ISSUE THREAD

**Issue by Master-Hash** [wpv-chan/cf-copilot-service#6]
测试服务报错：
```
JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```

（也许）原因：沉浸式翻译需要返回 JSON 而非 event stream

~~（我手上没有 OpenAI 的 api key 或者文档，不太清楚返回的 JSON 应该是什么格式，否则我大概可以自己来修）~~

更新：已经修了，需要的话我随时 pr

**Comment by wpv-chan** [comment]
确实，之前没考虑到这个问题，欢迎PR
